name: Deploy on Changes to Next.js Apps
on:
  pull_request:
    branches:
      - main
    types: [synchronize]
    paths:
      - 'apps/web/**'
      - 'apps/web/*'
      - 'apps/docs/**'
      - 'apps/docs/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Determine changes
      id: diff
      run: |
        diff=$(git diff --name-only HEAD $(git merge-base HEAD ${{ github.base_ref }}))
        echo "Changes detected: $diff"
        echo "diff=$diff" >> $GITHUB_ENV
    - name: Deploy web changes
      if: ${{ contains(env.diff, 'apps/web') }}
      run: |
        curl https://api.vercel.com/v1/integrations/deploy/prj_gMacbOOPHFgcG68cSURKttHFBCMj/IA81oGLHua
    - name: Deploy docs changes
      if: ${{ contains(env.diff, 'apps/docs') }}
      run: |
        curl https://api.vercel.com/v1/integrations/deploy/prj_kSMzWzQkxLTCqV7DI67hVgXuPYO2/vEJckOuzyq
