name: Deploy on Changes to Next.js Apps
on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'apps/web/*'
      - 'apps/docs/**'
      - 'apps/docs/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for comparing changes to past commits

      - name: Get changed packages
        id: turborepoChanges
        # uses: 94726/action-turborepo-changes@v1.0.0
        uses: 94726/action-turborepo-changes@2f392aee0d6b90803c0551ea774c254451fd92be

      - name: Deploy web to dev.domain.com
        if: contains(fromJson(steps.turborepoChanges.outputs.package_names), 'web')
        run: curl https://api.vercel.com/v1/integrations/deploy/prj_gMacbOOPHFgcG68cSURKttHFBCMj/IA81oGLHua

      - name: Deploy docs to domain.com
        if: contains(fromJson(steps.turborepoChanges.outputs.package_names), 'docs')
        run: curl https://api.vercel.com/v1/integrations/deploy/prj_kSMzWzQkxLTCqV7DI67hVgXuPYO2/vEJckOuzyq
