name: Deploy on Changes to Next.js Apps
on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'apps/web/*'
      - 'apps/docs/**'
      - 'apps/docs/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy web changes
        run: |
          curl https://api.vercel.com/v1/integrations/deploy/prj_gMacbOOPHFgcG68cSURKttHFBCMj/IA81oGLHua
      - name: Deploy docs changes
        run: |
          curl https://api.vercel.com/v1/integrations/deploy/prj_kSMzWzQkxLTCqV7DI67hVgXuPYO2/vEJckOuzyq
