name: TurboRepos Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install TurboRepo CLI
        run: pnpm i -g @turbo/turbo
      - name: Check for workspace changes
        run: turborepo diff
        id: check_changes
      - name: Deploy web changes
        if: ${{ contains(env.diff, 'apps/web') }}
        run: |
          curl https://api.vercel.com/v1/integrations/deploy/prj_gMacbOOPHFgcG68cSURKttHFBCMj/IA81oGLHua
      - name: Deploy docs changes
        if: ${{ contains(env.diff, 'apps/docs') }}
        run: |
          curl https://api.vercel.com/v1/integrations/deploy/prj_kSMzWzQkxLTCqV7DI67hVgXuPYO2/vEJckOuzyq
